title: Topic Modeling with Latent Dirichlet Allocation (LDA) for NIPS papers
description: Topic Modeling with Latent Dirichlet Allocation (LDA) for NIPS papers


github:
  id: 'your-github-name'
  href: 'https://github.com/'
  title: 'GitHub'
  fa-icon: 'fa-github-square'
